version: "3.7"

services: 
  tourneys-bot-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: tourneys-bot-docker
    expose:
      - 4000
    ports:
      - 4000
    command: npm run dev