name: Docker builds

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker logout
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD docker.io

      - name: docker build
        run: |
          docker build --tag tourneys_img .
  
      - name: docker tag
        run: |
          docker image tag tourneys_img nonce1/tourneys-bot
      
      - name: docker push
        run: |
          docker push nonce1/tourneys-bot