name: Backend deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker logout
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD docker.io

      - name: docker build
        run: |
          docker build --tag tourneys_img .

      - name: docker tag
        run: |
          docker image tag tourneys_img nonce1/tourneys-bot

      - name: docker push
        run: |
          docker push nonce1/tourneys-bot

  #heroku:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - uses: akhileshns/heroku-deploy@v3.12.12
  #      with:
  #        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
  #        heroku_app_name: "tourneys-bot"
  #        heroku_email: ${{ secrets.HEROKU_EMAIL }}
  #        usedocker: true
  #        docker_heroku_process_type: worker
  #      env:
  #        TOKEN: ${{ secrets.TOKEN }}

  heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0  # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          app_name: tourneys-bot # you aplication name
          dockerfile_path: '' # set the path to the folder wher the Dokerfile is located
          options: '' # Docker Build Options
          formation: '' # Docker Dyno Formation. By default is web
